// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: watchtowerrpc/watchtower.proto

package watchtowerrpc;

public final class WatchtowerOuterClass {
  private WatchtowerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:watchtowerrpc.GetInfoRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code watchtowerrpc.GetInfoRequest}
   */
  public  static final class GetInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:watchtowerrpc.GetInfoRequest)
      GetInfoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetInfoRequest.newBuilder() to construct.
    private GetInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInfoRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              watchtowerrpc.WatchtowerOuterClass.GetInfoRequest.class, watchtowerrpc.WatchtowerOuterClass.GetInfoRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof watchtowerrpc.WatchtowerOuterClass.GetInfoRequest)) {
        return super.equals(obj);
      }
      watchtowerrpc.WatchtowerOuterClass.GetInfoRequest other = (watchtowerrpc.WatchtowerOuterClass.GetInfoRequest) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(watchtowerrpc.WatchtowerOuterClass.GetInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code watchtowerrpc.GetInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:watchtowerrpc.GetInfoRequest)
        watchtowerrpc.WatchtowerOuterClass.GetInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                watchtowerrpc.WatchtowerOuterClass.GetInfoRequest.class, watchtowerrpc.WatchtowerOuterClass.GetInfoRequest.Builder.class);
      }

      // Construct using watchtowerrpc.WatchtowerOuterClass.GetInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoRequest_descriptor;
      }

      public watchtowerrpc.WatchtowerOuterClass.GetInfoRequest getDefaultInstanceForType() {
        return watchtowerrpc.WatchtowerOuterClass.GetInfoRequest.getDefaultInstance();
      }

      public watchtowerrpc.WatchtowerOuterClass.GetInfoRequest build() {
        watchtowerrpc.WatchtowerOuterClass.GetInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public watchtowerrpc.WatchtowerOuterClass.GetInfoRequest buildPartial() {
        watchtowerrpc.WatchtowerOuterClass.GetInfoRequest result = new watchtowerrpc.WatchtowerOuterClass.GetInfoRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof watchtowerrpc.WatchtowerOuterClass.GetInfoRequest) {
          return mergeFrom((watchtowerrpc.WatchtowerOuterClass.GetInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(watchtowerrpc.WatchtowerOuterClass.GetInfoRequest other) {
        if (other == watchtowerrpc.WatchtowerOuterClass.GetInfoRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        watchtowerrpc.WatchtowerOuterClass.GetInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (watchtowerrpc.WatchtowerOuterClass.GetInfoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:watchtowerrpc.GetInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:watchtowerrpc.GetInfoRequest)
    private static final watchtowerrpc.WatchtowerOuterClass.GetInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new watchtowerrpc.WatchtowerOuterClass.GetInfoRequest();
    }

    public static watchtowerrpc.WatchtowerOuterClass.GetInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetInfoRequest>() {
      public GetInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetInfoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInfoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInfoRequest> getParserForType() {
      return PARSER;
    }

    public watchtowerrpc.WatchtowerOuterClass.GetInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:watchtowerrpc.GetInfoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47; The public key of the watchtower.
     * </pre>
     *
     * <code>bytes pubkey = 1[json_name = "pubkey"];</code>
     */
    com.google.protobuf.ByteString getPubkey();

    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    java.util.List<java.lang.String>
        getListenersList();
    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    int getListenersCount();
    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    java.lang.String getListeners(int index);
    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    com.google.protobuf.ByteString
        getListenersBytes(int index);

    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    java.util.List<java.lang.String>
        getUrisList();
    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    int getUrisCount();
    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    java.lang.String getUris(int index);
    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    com.google.protobuf.ByteString
        getUrisBytes(int index);
  }
  /**
   * Protobuf type {@code watchtowerrpc.GetInfoResponse}
   */
  public  static final class GetInfoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:watchtowerrpc.GetInfoResponse)
      GetInfoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetInfoResponse.newBuilder() to construct.
    private GetInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInfoResponse() {
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
      listeners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              pubkey_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                listeners_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              listeners_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                uris_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              uris_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          listeners_ = listeners_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          uris_ = uris_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              watchtowerrpc.WatchtowerOuterClass.GetInfoResponse.class, watchtowerrpc.WatchtowerOuterClass.GetInfoResponse.Builder.class);
    }

    private int bitField0_;
    public static final int PUBKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <pre>
     *&#47; The public key of the watchtower.
     * </pre>
     *
     * <code>bytes pubkey = 1[json_name = "pubkey"];</code>
     */
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }

    public static final int LISTENERS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList listeners_;
    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    public com.google.protobuf.ProtocolStringList
        getListenersList() {
      return listeners_;
    }
    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    public int getListenersCount() {
      return listeners_.size();
    }
    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    public java.lang.String getListeners(int index) {
      return listeners_.get(index);
    }
    /**
     * <pre>
     *&#47; The listening addresses of the watchtower.
     * </pre>
     *
     * <code>repeated string listeners = 2[json_name = "listeners"];</code>
     */
    public com.google.protobuf.ByteString
        getListenersBytes(int index) {
      return listeners_.getByteString(index);
    }

    public static final int URIS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList uris_;
    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUrisList() {
      return uris_;
    }
    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    public int getUrisCount() {
      return uris_.size();
    }
    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    public java.lang.String getUris(int index) {
      return uris_.get(index);
    }
    /**
     * <pre>
     *&#47; The URIs of the watchtower.
     * </pre>
     *
     * <code>repeated string uris = 3[json_name = "uris"];</code>
     */
    public com.google.protobuf.ByteString
        getUrisBytes(int index) {
      return uris_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!pubkey_.isEmpty()) {
        output.writeBytes(1, pubkey_);
      }
      for (int i = 0; i < listeners_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, listeners_.getRaw(i));
      }
      for (int i = 0; i < uris_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uris_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!pubkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, pubkey_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < listeners_.size(); i++) {
          dataSize += computeStringSizeNoTag(listeners_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getListenersList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < uris_.size(); i++) {
          dataSize += computeStringSizeNoTag(uris_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUrisList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof watchtowerrpc.WatchtowerOuterClass.GetInfoResponse)) {
        return super.equals(obj);
      }
      watchtowerrpc.WatchtowerOuterClass.GetInfoResponse other = (watchtowerrpc.WatchtowerOuterClass.GetInfoResponse) obj;

      boolean result = true;
      result = result && getPubkey()
          .equals(other.getPubkey());
      result = result && getListenersList()
          .equals(other.getListenersList());
      result = result && getUrisList()
          .equals(other.getUrisList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPubkey().hashCode();
      if (getListenersCount() > 0) {
        hash = (37 * hash) + LISTENERS_FIELD_NUMBER;
        hash = (53 * hash) + getListenersList().hashCode();
      }
      if (getUrisCount() > 0) {
        hash = (37 * hash) + URIS_FIELD_NUMBER;
        hash = (53 * hash) + getUrisList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(watchtowerrpc.WatchtowerOuterClass.GetInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code watchtowerrpc.GetInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:watchtowerrpc.GetInfoResponse)
        watchtowerrpc.WatchtowerOuterClass.GetInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                watchtowerrpc.WatchtowerOuterClass.GetInfoResponse.class, watchtowerrpc.WatchtowerOuterClass.GetInfoResponse.Builder.class);
      }

      // Construct using watchtowerrpc.WatchtowerOuterClass.GetInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pubkey_ = com.google.protobuf.ByteString.EMPTY;

        listeners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return watchtowerrpc.WatchtowerOuterClass.internal_static_watchtowerrpc_GetInfoResponse_descriptor;
      }

      public watchtowerrpc.WatchtowerOuterClass.GetInfoResponse getDefaultInstanceForType() {
        return watchtowerrpc.WatchtowerOuterClass.GetInfoResponse.getDefaultInstance();
      }

      public watchtowerrpc.WatchtowerOuterClass.GetInfoResponse build() {
        watchtowerrpc.WatchtowerOuterClass.GetInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public watchtowerrpc.WatchtowerOuterClass.GetInfoResponse buildPartial() {
        watchtowerrpc.WatchtowerOuterClass.GetInfoResponse result = new watchtowerrpc.WatchtowerOuterClass.GetInfoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.pubkey_ = pubkey_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          listeners_ = listeners_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.listeners_ = listeners_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          uris_ = uris_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.uris_ = uris_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof watchtowerrpc.WatchtowerOuterClass.GetInfoResponse) {
          return mergeFrom((watchtowerrpc.WatchtowerOuterClass.GetInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(watchtowerrpc.WatchtowerOuterClass.GetInfoResponse other) {
        if (other == watchtowerrpc.WatchtowerOuterClass.GetInfoResponse.getDefaultInstance()) return this;
        if (other.getPubkey() != com.google.protobuf.ByteString.EMPTY) {
          setPubkey(other.getPubkey());
        }
        if (!other.listeners_.isEmpty()) {
          if (listeners_.isEmpty()) {
            listeners_ = other.listeners_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureListenersIsMutable();
            listeners_.addAll(other.listeners_);
          }
          onChanged();
        }
        if (!other.uris_.isEmpty()) {
          if (uris_.isEmpty()) {
            uris_ = other.uris_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUrisIsMutable();
            uris_.addAll(other.uris_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        watchtowerrpc.WatchtowerOuterClass.GetInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (watchtowerrpc.WatchtowerOuterClass.GetInfoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *&#47; The public key of the watchtower.
       * </pre>
       *
       * <code>bytes pubkey = 1[json_name = "pubkey"];</code>
       */
      public com.google.protobuf.ByteString getPubkey() {
        return pubkey_;
      }
      /**
       * <pre>
       *&#47; The public key of the watchtower.
       * </pre>
       *
       * <code>bytes pubkey = 1[json_name = "pubkey"];</code>
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The public key of the watchtower.
       * </pre>
       *
       * <code>bytes pubkey = 1[json_name = "pubkey"];</code>
       */
      public Builder clearPubkey() {
        
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList listeners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListenersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          listeners_ = new com.google.protobuf.LazyStringArrayList(listeners_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public com.google.protobuf.ProtocolStringList
          getListenersList() {
        return listeners_.getUnmodifiableView();
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public int getListenersCount() {
        return listeners_.size();
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public java.lang.String getListeners(int index) {
        return listeners_.get(index);
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public com.google.protobuf.ByteString
          getListenersBytes(int index) {
        return listeners_.getByteString(index);
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public Builder setListeners(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListenersIsMutable();
        listeners_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public Builder addListeners(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListenersIsMutable();
        listeners_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public Builder addAllListeners(
          java.lang.Iterable<java.lang.String> values) {
        ensureListenersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listeners_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public Builder clearListeners() {
        listeners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The listening addresses of the watchtower.
       * </pre>
       *
       * <code>repeated string listeners = 2[json_name = "listeners"];</code>
       */
      public Builder addListenersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureListenersIsMutable();
        listeners_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUrisIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          uris_ = new com.google.protobuf.LazyStringArrayList(uris_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public com.google.protobuf.ProtocolStringList
          getUrisList() {
        return uris_.getUnmodifiableView();
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public int getUrisCount() {
        return uris_.size();
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public java.lang.String getUris(int index) {
        return uris_.get(index);
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public com.google.protobuf.ByteString
          getUrisBytes(int index) {
        return uris_.getByteString(index);
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public Builder setUris(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrisIsMutable();
        uris_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public Builder addUris(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrisIsMutable();
        uris_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public Builder addAllUris(
          java.lang.Iterable<java.lang.String> values) {
        ensureUrisIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uris_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public Builder clearUris() {
        uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; The URIs of the watchtower.
       * </pre>
       *
       * <code>repeated string uris = 3[json_name = "uris"];</code>
       */
      public Builder addUrisBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureUrisIsMutable();
        uris_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:watchtowerrpc.GetInfoResponse)
    }

    // @@protoc_insertion_point(class_scope:watchtowerrpc.GetInfoResponse)
    private static final watchtowerrpc.WatchtowerOuterClass.GetInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new watchtowerrpc.WatchtowerOuterClass.GetInfoResponse();
    }

    public static watchtowerrpc.WatchtowerOuterClass.GetInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInfoResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetInfoResponse>() {
      public GetInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetInfoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInfoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInfoResponse> getParserForType() {
      return PARSER;
    }

    public watchtowerrpc.WatchtowerOuterClass.GetInfoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_watchtowerrpc_GetInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_watchtowerrpc_GetInfoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_watchtowerrpc_GetInfoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_watchtowerrpc_GetInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036watchtowerrpc/watchtower.proto\022\rwatcht" +
      "owerrpc\"\020\n\016GetInfoRequest\"[\n\017GetInfoResp" +
      "onse\022\026\n\006pubkey\030\001 \001(\014R\006pubkey\022\034\n\tlistener" +
      "s\030\002 \003(\tR\tlisteners\022\022\n\004uris\030\003 \003(\tR\004uris2V" +
      "\n\nWatchtower\022H\n\007GetInfo\022\035.watchtowerrpc." +
      "GetInfoRequest\032\036.watchtowerrpc.GetInfoRe" +
      "sponseB5Z3github.com/lightningnetwork/ln" +
      "d/lnrpc/watchtowerrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_watchtowerrpc_GetInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_watchtowerrpc_GetInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_watchtowerrpc_GetInfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_watchtowerrpc_GetInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_watchtowerrpc_GetInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_watchtowerrpc_GetInfoResponse_descriptor,
        new java.lang.String[] { "Pubkey", "Listeners", "Uris", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
